server:
  port: 8080

spring:
  codec:
    max-in-memory-size: 10MB
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:flightDB
    username: sa
    password: 
    driverClassName: org.h2.Driver
    schema: schema.sql
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
airbook:
  secret: 5b50d80c7dc7ae8bb1b1433cc0b99ecd2ac8397a555c6f75cb8a619ae35a0c3d3245566ac5
  algorithm: HmacSHA256