CREATE TABLE AIRPORT (
	AIRPORT_ID INTEGER NOT NULL AUTO_INCREMENT,
	ICAO VARCHAR(4) NOT NULL,
	IATA VARCHAR(3) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	STATE VARCHAR(99) NOT NULL,
	COUNTRY VARCHAR(2) NOT NULL,
	PRIMARY KEY (AIRPORT_ID)
);